#!/usr/bin/env php
<?php

if (
    (!@include __DIR__.'/../../.composer/autoload.php')
    && (!@include __DIR__.'/vendor/.composer/autoload.php')
) {
    die('You must set up the project dependencies, run the following commands:'
            ."\n".
        'curl -s http://getcomposer.org/installer | php'."\n".
        'php composer.phar install'."\n");
}

use Phpsog\Command\BuildCommand;
use Phpsog\Command\HelpCommand;
use Phpsog\Command\InitCommand;
use Phpsog\Command\UnknownCommand;
use Phpsog\Command\VersionCommand;

use Phpsog\Factory;

// Convert internal errors to exceptions
set_error_handler(function ($errno, $errstr, $errfile, $errline) {
    throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
});

try {

    $f = new Factory();
    $app = $f->createNewApplication();

    $argv = $_SERVER['argv'];

    $cmd = null;

    if ($argv[1] === 'version' || $argv[1] === '--version') {
        $cmd = new VersionCommand($argv);
    } else if ($argv[1] === 'init') {
        $cmd = new InitCommand($argv);
    } else if ($argv[1] === 'help' || $argv[1] === '--help') {
        $cmd = new HelpCommand($argv);
    } else if ($argv[1] === 'build') {
        $cmd = new BuildCommand($argv);
    } else {
        $cmd = new UnknownCommand($argv);
    }

    $app->executeCommand($cmd);

} catch (Exception $e) {
    die('Error: ' . $e->getMessage() . "\n");
}
