#!/usr/bin/env php
<?php

if (
    (!@include __DIR__.'/../../.composer/autoload.php')
    && (!@include __DIR__.'/vendor/.composer/autoload.php')
) {
    die('You must set up the project dependencies, run the following commands:'
            ."\n".
        'curl -s http://getcomposer.org/installer | php'."\n".
        'php composer.phar install'."\n");
}

use Phpsog\Application;
use Phpsog\Exporter;
use Phpsog\Logger;
use Kaloa\Filesystem\PathHelper;

try {
    $params = array(
        'config' => ''
    );

    $dispatched = false;

    if ($_SERVER['argc'] !== 2) {
        throw new Exception('Wrong argument count');
    } else {
        if ($_SERVER['argv'][1] === '--version') {
            echo 'phpsog ' . Application::VERSION . "\n";
            $dispatched = true;
        } else {
            $params['config'] = $_SERVER['argv'][1];
        }
    }

    if (!$dispatched) {
        if (is_dir($params['config'])) {
            $params['config'] .= '/phpsog.ini';
        }

        $ph = new PathHelper();
        $logger = new Logger();

        $phpsog = new Application(new Exporter($ph, $logger), $ph);

        $phpsog->loadConfig($params['config']);

        $phpsog->sanitizeEnvironment();

        $phpsog->processHtmlProvider();
        $phpsog->processResources();
    }

} catch (Exception $e) {
    die('Error: ' . $e->getMessage() . "\n");
}
