<?php

/* @var $this Phpsog\Provider\Html\Provider */
$this->setTitle('About');

$x['menuActive'] = 'about';

?>

<h1>About</h1>

<h2>What is phpsog?</h2>

<p>Simply said: If you are using PHP’s include mechanism on the server to add the same navigation menu to all of your otherwise non-dynamic content pages, phpsog can be used to generate all of the individual HTML documents from templates on the client side. Using this approach, there is no longer a need to execute PHP code on the server.</p>

<p>Open the <a href="readme.html">README file</a>.</p>

<p>Author’s home page: <a href="http://www.ermshaus.org/">ermshaus.org</a></p>
