<?php
/* @var $this Phpsog\Provider\Html\Provider */
$this->setTitle('Home');

$x['menuActive'] = 'home';

?>

<p>phpsog (PHP Static Output Generator) is a build tool to generate static content from PHP source code. <a href="about.html">Learn more</a></p>

<h2>Status</h2>

<p style="font-size: small; text-align: left;"><span style="padding: 3px; background: #F43E14; color: white;">Apr 23rd, 2012</span></p>

<p>I am working on the first tagged release (0.1.0) in order to provide a stable version with a fixed <abbr title="Application programming interface ">API</abbr> that can be used as a dependency within other projects. Do not use non-tagged versions in production as the public API <em>will</em> change without notice. Individual commits also might introduce bugs or changes that lead to a temporarily broken state of the whole code base.</p>

<p>phpsog tries to honor the concept of <a href="http://semver.org/">Semantic Versioning</a>. Backwards incompatible changes to the API are only introduced on minor version number changes (0.1.0 &rarr; 0.2.0).</p>

<p style="font-size: small; text-align: right;"><span style="padding: 3px; background: #ddd;">mermshaus</span></p>
