<?php

/* @var $this Phpsog\Provider\Html\Provider */

// Menu hacks
$x['menuActive'] = (isset($x['menuActive'])) ? $x['menuActive'] : '';

$p = $pathToRoot;

?><!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <title><?=$this->escape($title)?></title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,700italic,400italic' rel='stylesheet' type='text/css' />
        <link rel="stylesheet" type="text/css" href="<?=$p?>/styles.css" />
    </head>

    <body>

<a href="https://github.com/mermshaus/phpsog"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://a248.e.akamai.net/assets.github.com/img/7afbc8b248c68eb468279e8c17986ad46549fb71/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub"></a>

        <header>
            <a href="<?=$p?>/">
                <?php if ($p === '.' && $x['menuActive'] === 'home') : ?>
                    <img src="images/phpsog-big.png" />
                <?php else : ?>
                    <img src="<?=$p?>/images/phpsog-small.png" />
                <?php endif; ?>
            </a>
        </header>

        <ul class="cf menu">
            <li<?=($x['menuActive']==='docs/concepts')?' class="active"':''?>><a href="<?=$p?>/docs/concepts.html">Concepts</a></li>
            <li<?=($x['menuActive']==='docs/config')?' class="active"':''?>><a href="<?=$p?>/docs/config.html">Config</a></li>
            <li<?=($x['menuActive']==='docs/cli')?' class="active"':''?>><a href="<?=$p?>/docs/cli.html">CLI</a></li>
            <li<?=($x['menuActive']==='docs/recipes')?' class="active"':''?>><a href="<?=$p?>/docs/recipes.html">Recipes</a></li>
            <li<?=($x['menuActive']==='about')?' class="active"':''?>><a href="<?=$p?>/about.html">About</a></li>
        </ul>

        <div class="content">

        <?=$content?>

        </div>

        <footer>
            <p>Last compiled on: <?=$this->escape(date('Y-m-d H:i:s e'))?></p>
        </footer>

    </body>

</html>
