<?php

namespace Phpsog;

// Menu hacks
$x['menuActive'] = (isset($x['menuActive'])) ? $x['menuActive'] : '';

$p = $pathToRoot;

?><!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <title><?=e($title)?></title>
        <link rel="stylesheet" type="text/css" href="<?=$p?>/styles.css" />
    </head>

    <body>

        <header>
        <a href="<?=$p?>/"><img src="<?=$p?>/images/phpsog.png" /> phpsog</a>
        </header>

        <ul class="cf menu">
            <li<?=($x['menuActive']==='home')?' class="active"':''?>><a href="<?=$p?>/">Home</a></li>
            <li<?=($x['menuActive']==='docs/concepts')?' class="active"':''?>><a href="<?=$p?>/docs/concepts.html">Concepts</a></li>
            <li<?=($x['menuActive']==='docs/config')?' class="active"':''?>><a href="<?=$p?>/docs/config.html">Config</a></li>
            <li<?=($x['menuActive']==='docs/cli')?' class="active"':''?>><a href="<?=$p?>/docs/cli.html">CLI</a></li>
            <li<?=($x['menuActive']==='docs/recipes')?' class="active"':''?>><a href="<?=$p?>/docs/recipes.html">Recipes</a></li>
            <li<?=($x['menuActive']==='about')?' class="active"':''?>><a href="<?=$p?>/about.html">About</a></li>
        </ul>

        <div class="content">

        <?=$content?>

        </div>

        <footer>
            <p>Last compiled on: <?=e(date('Y-m-d H:i:s e'))?></p>
        </footer>

    </body>

</html>
