<?php

namespace org\ermshaus\phpsog;

// Menu hacks
$x['menuActive'] = (isset($x['menuActive'])) ? $x['menuActive'] : '';

?><!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <title><?=e($title)?></title>
        <link rel="stylesheet" type="text/css" href="styles.css" />
    </head>

    <body>

        <a href="./"><img src="phpsog.png" /></a>

        <ul class="menu">
            <li<?=($x['menuActive']==='./')?' class="active"':''?>><a href="./">Home</a></li>
            <li<?=($x['menuActive']==='about.html')?' class="active"':''?>><a href="about.html">About</a></li>
            <li<?=($x['menuActive']==='contact.html')?' class="active"':''?>><a href="contact.html">Contact</a></li>
        </ul>

        <?=$content?>

    </body>

</html>
