<?php

/* @var $this Phpsog\Provider\Html\Provider */
$this->setTitle('Command-line interface');

$x['menuActive'] = 'docs/cli';

?>

<h1>Command-line interface</h1>

<pre><code>phpsog &lt;project-path&gt;

phpsog --version</code></pre>

<dl>
    <dt><var>project-path</var></dt>
    <dd>This is either a path to a config file or a path to a directory containing a phpsog.ini file.</dd>

    <dt><code>--version</code></dt>
    <dd>Prints version info and exits.</dd>
</dl>
