<?php

/* @var $this Phpsog\Provider\Html\Provider */
$this->setTitle('Concepts');

$x['menuActive'] = 'docs/concepts';

?>

<h1>Concepts</h1>

<dl>
    <dt>phpsog directory</dt>
    <dd>The directory containing phpsog’s internal source code and data files. It can be changed through the global command-line option <var>--phpsog-dir</var>. The setting defaults to the directory of the phpsog executable. Usually, you won’t have to touch this.</dd>
    <dt>project directory</dt>
    <dd>-</dd>
    <dt>export directory</dt>
    <dd>-</dd>
</dl>

<h2>Providers</h2>

<h3>Asset</h3>

<p>A provider to generate (as of now, that means: copy) assets (CSS files, JS files, …).</p>

<h3>Html</h3>

<p>A provider to generate HTML output.</p>

<h2>Basic classes</h2>

<h3>Exporter</h3>

<p>This class is the low-level workhorse that performs all file system write operations during the export process.</p>

<p>Providers need to know an instance of this class.</p>
