<?php

/* @var $this Phpsog\Provider\Html\Provider */
$this->setTitle('Concepts');

$x['menuActive'] = 'docs/concepts';

?>

<h1>Concepts</h1>

<h2>Providers</h2>

<h3>Asset</h3>

<p>A provider to generate (as of now, that means: copy) assets (CSS files, JS files, …).</p>

<h3>Html</h3>

<p>A provider to generate HTML output.</p>

<h2>Basic classes</h2>

<h3>Exporter</h3>

<p>This class is the low-level workhorse that performs all file system write operations during the export process.</p>

<p>Providers need to know an instance of this class.</p>
