<?php

/* @var $this Phpsog\Provider\Html\Provider */
$this->setTitle('Config');

$x['menuActive'] = 'docs/config';

$json = json_decode(file_get_contents(__DIR__ . '/settings.json'));

?>

<h1>Config</h1>

<h2>Settings</h2>

<dl>
<?php foreach ($json->data as $d) : ?>

    <?php
    $default = $d->default;
    if (in_array($d->type, array('string', 'path'))) {
        $default = '"' . $default . '"';
    }
    ?>

<dt><code><?=$d->name?></code> (<?=$d->type?>, default: <?=$default?>)</dt>
<dd><?=$d->description?></dd>

<?php endforeach; ?>
</dl>
